# Node.js with gulp
# Build a Node.js application using the gulp task runner.
# https://aka.ms/yaml
queue: 'Hosted Linux Preview'
steps:
#  - task: NodeTool@0
#    inputs:
#      versionSpec: '8.x' 

  - task: Npm@1
    inputs:
      command: 'install'

  - task: Gulp@0
    inputs:
      gulpFile: 'gulpfile.js'
      targets: ''
      publishJUnitResults: true

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
